// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	model "github.com/scys12/modul-go/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// IProductRepo is an autogenerated mock type for the IProductRepo type
type IProductRepo struct {
	mock.Mock
}

// BuyProduct provides a mock function with given fields: _a0
func (_m *IProductRepo) BuyProduct(_a0 int) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckUsernameAndEmail provides a mock function with given fields: _a0, _a1
func (_m *IProductRepo) CheckUsernameAndEmail(_a0 string, _a1 string) (bool, error) {
	ret := _m.Called(_a0, _a1)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteProduct provides a mock function with given fields: _a0, _a1
func (_m *IProductRepo) DeleteProduct(_a0 int, _a1 int) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAvailableProducts provides a mock function with given fields:
func (_m *IProductRepo) GetAvailableProducts() ([]model.Product, error) {
	ret := _m.Called()

	var r0 []model.Product
	if rf, ok := ret.Get(0).(func() []model.Product); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCurrentUserProduct provides a mock function with given fields: _a0, _a1
func (_m *IProductRepo) GetCurrentUserProduct(_a0 int, _a1 int) (model.Product, error) {
	ret := _m.Called(_a0, _a1)

	var r0 model.Product
	if rf, ok := ret.Get(0).(func(int, int) model.Product); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(model.Product)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProduct provides a mock function with given fields: _a0
func (_m *IProductRepo) GetProduct(_a0 int) (model.Product, error) {
	ret := _m.Called(_a0)

	var r0 model.Product
	if rf, ok := ret.Get(0).(func(int) model.Product); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(model.Product)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSellerProducts provides a mock function with given fields: _a0
func (_m *IProductRepo) GetSellerProducts(_a0 int) ([]model.Product, error) {
	ret := _m.Called(_a0)

	var r0 []model.Product
	if rf, ok := ret.Get(0).(func(int) []model.Product); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertProduct provides a mock function with given fields: _a0
func (_m *IProductRepo) InsertProduct(_a0 model.Product) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Product) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateProduct provides a mock function with given fields: _a0
func (_m *IProductRepo) UpdateProduct(_a0 model.Product) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Product) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
