// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// IUserDelivery is an autogenerated mock type for the IUserDelivery type
type IUserDelivery struct {
	mock.Mock
}

// CreateNewUser provides a mock function with given fields: _a0, _a1
func (_m *IUserDelivery) CreateNewUser(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// GetUserDetail provides a mock function with given fields: _a0, _a1
func (_m *IUserDelivery) GetUserDetail(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// LoginUser provides a mock function with given fields: _a0, _a1
func (_m *IUserDelivery) LoginUser(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}
